### ISSUE TITLE
Cube tarball related properties should be optional

### ISSUE THREAD

**Issue by aristizabal95** [johnugeorge/medperf#1]
With the current implementation, every cube must have additional files, or specifically the `tarball_url` and `tarball_hash` properties. This is not the case for every cube, as some require no additional files to run.

I'd say we should make the `tarball_url` optional, and `tarball_hash` conditionally optional based on the presence of a tarball url.

**Comment by johnugeorge** [comment]
From https://github.com/johnugeorge/medperf/commit/e6a0ffaa3ae7cfed1f7ce36b9cae3faac0f103e3

`tarball_url` and `tarball_hash` are made optional. We will add conditional optional when we add a validation check. Also `git_mlcube_url` and `git_parameters_url` are added instead of earlier `git_url`

**Comment by johnugeorge** [comment]
Closing this issue as fix is merged
