### ISSUE TITLE
Should the benchmarkDataset model include a `initiated_by` field?

### ISSUE THREAD

**Issue by aristizabal95** [johnugeorge/medperf#2]
This is more of an expectation/question I had while working on this.

In the initial workflow, the benchmarkDataset request is generated by the data owner. But, this is not generally the case. If I create a new benchmark and reuse a data preparation cube, I should be able to request data owners association to my benchmark. Because of this, we need to know who is requesting association so that the other party can approve/deny the request.

**Comment by johnugeorge** [comment]
Do you mean, benchmark owner can also initiate the  dataset association api  given in https://github.com/johnugeorge/medperf/blob/c802ddb2ddf78d536bb42b1fd9c0857fe9a2461f/server.sh#L119

**Comment by johnugeorge** [comment]
Closing this issue as fix is merged
